[package]
name = "spritter"
version = "0.1.0"
edition = "2021"
authors = ["fgardt <me@fgardt.dev>"]
description = "Spritesheet generator for factorio"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
nursery = "warn"
pedantic = "warn"
unwrap_used = "warn"
expect_used = "warn"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
error-stack = "0.4"
image = "0.25"
thiserror = "1.0"
